config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :products do
    resources :search_terms
  end

  root to: 'products#index'

end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :user
  has_many :search_terms, dependent: :destroy

  validates :asin, presence: true, length: { minimum: 10 }
  validates :user, presence: true

  def name
    metadata.fetch('title')
  end
end

app/models/rank.rb
class Rank < ActiveRecord::Base
  belongs_to :search_term
  validates :search_term, presence: true
  validates :date, presence: true
  validates :data, presence: true
end

app/models/search_term.rb
class SearchTerm < ActiveRecord::Base
  belongs_to :product
  has_many :ranks, dependent: :destroy

  validates :product, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :products, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = current_user.products
  end

  def new
    @product = current_user.products.new
  end

  def create
    @operation = CreateProductService.prepare(params, current_user)
    @operation.perform!
    if @operation.succeed?
      flash[:notice] = 'Product added!'
      redirect_to products_path
    else
      flash[:alert] = @operation.errors
      @product = @operation.product
      render :new
    end
  end
end

app/controllers/search_terms_controller.rb
class SearchTermsController < ApplicationController

  def new
    @product = current_user.products.find_by(id: params[:product_id])
  end

  def create
    @operation = CreateSearchTermsService.prepare(params, current_user)
    @operation.perform!
    if @operation.succeed?
      flash[:notice] = 'Search Terms added!'
      redirect_to products_path
    else
      flash[:alert] = @operation.errors
      @product = @operation.product
      render :new
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def vacuum
    @vacuum ||= load_vacuum_client
  end

  def load_vacuum_client
    request = Vacuum.new
    request.configure(aws_access_key_id: Rails.configuration.amazon['aws_access_key_id'],
                      aws_secret_access_key: Rails.configuration.amazon['aws_secret_access_key'],
                      associate_tag: Rails.configuration.amazon['associate_tag'])
    request
  end
end

app/helpers/products_controller_helper.rb
module ProductsControllerHelper
end

app/views/layouts/application.html.slim
doctype html
html lang="en"
  head
    meta charset="utf-8"
    meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1"
    meta name="viewport" content="width=device-width, initial-scale=1.0"
    title= content_for?(:title) ? yield(:title) : "Amazone"
    = csrf_meta_tags
    = stylesheet_link_tag "application", :media => "all"
    = favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144'
    = favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114'
    = favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72'
    = favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png'
    = favicon_link_tag 'favicon.ico', :rel => 'shortcut icon'
    = javascript_include_tag "application"
    /! Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js"


  body
    .navbar.navbar-default.navbar-static-top
        .container
          button.navbar-toggle type="button" data-toggle="collapse" data-target=".navbar-responsive-collapse"
            span.icon-bar
            span.icon-bar
            span.icon-bar
          a.navbar-brand href="#"Amazone
          .navbar-collapse.collapse.navbar-responsive-collapse
            ul.nav.navbar-nav.navbar-left
              li= link_to "Products", "/products"
            ul.nav.navbar-nav.navbar-right
              - if user_signed_in?
                li= link_to('Logout', destroy_user_session_path, :method => :delete)
              - else
                li= link_to('Login', new_user_session_path)


    .container
      .row
        .col-lg-9
          = bootstrap_flash
          = yield
        .col-lg-3
          .well.sidebar-nav
            h3 Sidebar
            ul.nav.nav-list
              li.nav-header Sidebar
              li= link_to "Link 1", "/path1"
              li= link_to "Link 2", "/path2"
              li= link_to "Link 3", "/path3"

      footer
        p &copy; Company 2016

app/views/products/index.html.slim
= link_to('Add product', new_product_path, class: 'btn btn-primary pull-right')
br
br
- if @products.empty?
  h2 Add your first product!
- else
  dl
    - @products.each do |product|
      dd
        = product.name
        = link_to('Add SearchTerms', new_product_search_term_path(product), class: 'btn btn-primary pull-right')
      dt
        dl
          - product.search_terms.each do |term|
            dd
              = term.term
      br

app/views/products/new.html.slim
= simple_form_for(@product, html: { class: 'form-horizontal' }) do |form|
  = form.input :asin
  = form.button :submit

app/views/search_terms/new.html.slim
= form_tag(product_search_terms_path(@product)) do |f|
  = text_area_tag(:search_terms, '', size: "80x10")
  br
  = button_tag('Submit', {class: 'btn btn-primary'})